// Rust Academy — application logic shared by Windows and Android.
//
// The Slint UI is generated by build.rs from ui/app.slint. This file owns the
// course data, state transitions, persistence and wiring between UI callbacks
// and data. Everything runs on the UI thread (which is also the Android main
// thread), keeping the implementation simple and portable.

slint::include_modules!();

mod content;

use slint::{ComponentHandle, SharedString, Timer, TimerMode, VecModel};
use std::cell::RefCell;
use std::path::{Path, PathBuf};
use std::rc::Rc;
use std::time::Duration;

#[derive(Default, serde::Serialize, serde::Deserialize)]
struct SaveData {
    xp: i32,
    streak: i32,
    last_day: String,
    best_quiz: i32,
    done: Vec<i32>,
    best: Vec<(i32, i32)>,
    opened_cheats: Vec<i32>,
    scenario: i32,
    scenario_line: i32,
    quiz_answered: i32,
    accent: i32,
}

impl SaveData {
    fn best_for(&self, id: i32) -> i32 {
        self.best
            .iter()
            .find(|(lesson, _)| *lesson == id)
            .map(|(_, score)| *score)
            .unwrap_or(0)
    }

    fn set_best(&mut self, id: i32, score: i32) {
        if let Some(entry) = self.best.iter_mut().find(|(lesson, _)| *lesson == id) {
            entry.1 = entry.1.max(score);
        } else {
            self.best.push((id, score));
        }
        self.best_quiz = self.best_quiz.max(score);
    }
}

struct AppState {
    data: SaveData,
    lessons: Vec<LessonInfo>,
    modules: Vec<ModuleInfo>,
    scenarios: Vec<content::Scenario>,
    lesson_id: i32,
    quiz: Vec<QuizQ>,
    quiz_index: usize,
    quiz_correct: i32,
    scenario_index: usize,
    scenario_step: usize,
    timer: Option<Timer>,
    playing: bool,
    save_dir: PathBuf,
}

impl AppState {
    fn new(save_dir: PathBuf) -> Self {
        let data = load(&save_dir);
        let mut opened = data.opened_cheats.clone();
        if opened.is_empty() {
            opened.push(1);
        }
        let mut data = data;
        data.opened_cheats = opened;

        Self {
            data,
            lessons: content::lessons(),
            modules: content::modules(),
            scenarios: content::scenarios(),
            lesson_id: 1,
            quiz: Vec::new(),
            quiz_index: 0,
            quiz_correct: 0,
            scenario_index: 0,
            scenario_step: 0,
            timer: None,
            playing: false,
            save_dir,
        }
    }

    // ------------------------------------------------------------------
    // Helpers
    // ------------------------------------------------------------------

    fn save(&self) {
        let _ = std::fs::create_dir_all(&self.save_dir);
        let path = self.save_dir.join("rust-academy.json");
        if let Ok(json) = serde_json::to_vec_pretty(&self.data) {
            let _ = std::fs::write(path, json);
        }
    }

    fn done_count(&self) -> usize {
        self.lessons
            .iter()
            .filter(|l| self.data.done.contains(&l.id))
            .count()
    }

    fn best_score(&self) -> i32 {
        self.data.best_quiz
    }

    fn lesson(&self, id: i32) -> Option<&LessonInfo> {
        self.lessons.iter().find(|l| l.id == id)
    }

    fn stop_playing(&mut self, ui: &MainWindow) {
        self.playing = false;
        if let Some(timer) = self.timer.take() {
            timer.stop();
        }
        ui.set_playing(false);
    }

    // ------------------------------------------------------------------
    // Initial UI population
    // ------------------------------------------------------------------

    fn push_lessons(&self, ui: &MainWindow) {
        ui.set_lessons(models(self.lessons.clone()));
    }

    fn push_home_lessons(&self, ui: &MainWindow) {
        let filtered = {
            let mut out: Vec<LessonInfo> = self
                .lessons
                .iter()
                .filter(|l| l.status == 1)
                .cloned()
                .collect();
            if out.is_empty() {
                out = self
                    .lessons
                    .iter()
                    .filter(|l| l.status == 2)
                    .rev()
                    .take(3)
                    .cloned()
                    .collect();
            }
            if out.is_empty() {
                out = self.lessons.iter().take(3).cloned().collect();
            }
            out
        };
        ui.set_home_lessons(models(filtered));
    }

    fn push_week(&self, ui: &MainWindow) {
        ui.set_week(models(content::week(self.data.xp.min(100))));
    }

    fn push_modules(&self, ui: &MainWindow) {
        let mut modules = content::modules();
        for m in &mut modules {
            let ids: Vec<i32> = self
                .lessons
                .iter()
                .filter(|l| l.module == m.id)
                .map(|l| l.id)
                .collect();
            m.done = ids
                .iter()
                .filter(|id| self.data.done.contains(id))
                .count() as i32;
            m.total = ids.len() as i32;
        }
        self.modules = modules.clone();
        ui.set_modules(models(modules));
    }

    fn push_cheatsheet(&self, ui: &MainWindow) {
        let mut entries = content::cheatsheet();
        for e in &mut entries {
            e.open = self.data.opened_cheats.contains(&e.id);
        }
        ui.set_cheatsheet(models(entries));
        ui.set_cheat_cats(models(
            vec!["All", "Basics", "Ownership", "Patterns", "Tools"]
                .into_iter()
                .map(SharedString::from)
                .collect(),
        ));
    }

    fn push_achievements(&self, ui: &MainWindow) {
        let items = content::achievements(self.done_count(), self.best_score(), self.data.streak);
        let earned = items.iter().filter(|a| a.earned).count();
        let header = format!(
            "{earned} of {} badges earned",
            items.len()
        );
        ui.set_achievements(models(items));
        ui.set_ach_header(header.into());
    }

    fn push_scenario_names(&self, ui: &MainWindow) {
        let names: Vec<SharedString> = self
            .scenarios
            .iter()
            .map(|s| s.name.clone().into())
            .collect();
        ui.set_scenario_names(models(names));
    }

    fn apply_scenario_step(&mut self, ui: &MainWindow) {
        let scenario = &self.scenarios[self.scenario_index];
        let step = &scenario.steps[self.scenario_step];
        ui.set_current_line(step.line);
        ui.set_step_note(step.note.clone().into());
        let vars: Vec<VarEntry> = step
            .vars
            .iter()
            .map(|(name, value)| VarEntry {
                name: name.clone().into(),
                value: value.clone().into(),
                dirty: true,
            })
            .collect();
        ui.set_vars(models(vars));
    }

    fn push_scenario(&mut self, ui: &MainWindow) {
        self.scenario_index = self
            .data
            .scenario
            .clamp(0, self.scenarios.len() as i32 - 1) as usize;
        if self.scenario_step >= self.scenarios[self.scenario_index].steps.len() {
            self.scenario_step = 0;
        }
        let scenario = &self.scenarios[self.scenario_index];
        ui.set_scenario(self.scenario_index as i32);
        ui.set_scenario_title(scenario.title.clone().into());
        ui.set_scenario_blurb(scenario.blurb.clone().into());
        ui.set_code_lines(models(scenario.lines.clone()));
        self.apply_scenario_step(ui);
    }

    fn push_quiz(&self, ui: &MainWindow) {
        ui.set_quiz(models(self.quiz.clone()));
    }

    fn refresh_stat_ui(&self, ui: &MainWindow) {
        ui.set_xp(self.data.xp);
        ui.set_streak(self.data.streak);
        ui.set_lessons_done(self.done_count() as i32);
        ui.set_lessons_total(self.lessons.len() as i32);
        ui.set_quiz_best(self.best_score());
        ui.set_greeting(greeting().into());
        ui.set_accent_index(self.data.accent);
    }

    fn refresh_lesson_ui(&self, ui: &MainWindow) {
        self.push_lessons(ui);
        self.push_home_lessons(ui);
        self.push_modules(ui);
        self.push_achievements(ui);
        self.push_week(ui);
        ui.set_lessons_search(SharedString::default());
        ui.set_cheat_search(SharedString::default());
    }

    fn refresh_all(&mut self, ui: &MainWindow) {
        self.refresh_stat_ui(ui);
        self.refresh_lesson_ui(ui);
        self.push_cheatsheet(ui);
        self.push_scenario(ui);
        self.update_quiz_property(ui);
    }

    fn update_quiz_property(&self, ui: &MainWindow) {
        ui.set_quiz_index(self.quiz_index as i32);
        ui.set_quiz_count(self.quiz.len() as i32);
        ui.set_quiz_correct(self.quiz_correct);
        ui.set_quiz_done(false);
        ui.set_quiz_phase(0);
        ui.set_quiz_progress(quiz_progress(self.quiz_index, self.quiz.len()));
        ui.set_quiz_result(SharedString::default());
        ui.set_quiz_result_sub(SharedString::default());
    }

    // ------------------------------------------------------------------
    // Navigation
    // ------------------------------------------------------------------

    fn navigate(&mut self, ui: &MainWindow, page: i32) {
        if page != 4 && self.playing {
            self.stop_playing(ui);
        }
        if page == 4 {
            self.push_scenario(ui);
        }
        if page == 5 {
            self.push_cheatsheet(ui);
        }
        if page == 6 {
            self.push_achievements(ui);
        }
        ui.set_page(page);
    }

    fn go_back(&mut self, ui: &MainWindow) {
        let target = match ui.get_page() {
            2 | 3 => 1,
            4 => 0,
            5 | 6 => 1,
            8 => 7,
            _ => 0,
        };
        self.navigate(ui, target);
    }

    fn open_lesson(&mut self, ui: &MainWindow, id: i32) {
        if let Some(lesson) = self.lesson(id) {
            if lesson.status == 0 {
                return;
            }
            self.lesson_id = id;
            ui.set_lesson_icon(lesson.icon.clone());
            let module = self
                .modules
                .iter()
                .find(|m| m.id == lesson.module)
                .map(|m| m.title.clone())
                .unwrap_or_else(|| "Rust Course".into());
            ui.set_lesson_module(module);
            ui.set_lesson_title(lesson.title.clone());
            ui.set_lesson_subtitle(lesson.subtitle.clone());
            ui.set_lesson_duration(lesson.duration.clone());
            ui.set_lesson_xp(lesson.xp.clone());
            ui.set_lesson_status(lesson.status);
            ui.set_lesson_best(lesson.best.clone());
            ui.set_blocks(models(content::blocks_lesson(id)));
            ui.set_code_lines(models(content::code_lines_lesson(id)));
            self.reset_quiz_data(ui);
            ui.set_page(2);
        }
    }

    fn mark_complete(&mut self, ui: &MainWindow) {
        let id = self.lesson_id;
        if !self.data.done.contains(&id) {
            self.data.done.push(id);
            if let Some(lesson) = self.lesson(id) {
                self.data.xp += lesson.xp.parse::<i32>().unwrap_or(40);
            }
            self.save();
        }
        if let Some(lesson) = self.lesson(id) {
            ui.set_lesson_status(2);
        }
        self.refresh_lesson_ui(ui);
    }

    // ------------------------------------------------------------------
    // Quiz
    // ------------------------------------------------------------------

    fn reset_quiz_data(&mut self, ui: &MainWindow) {
        self.quiz = content::quiz_lesson(self.lesson_id);
        self.quiz_index = 0;
        self.quiz_correct = 0;
        self.update_quiz_property(ui);
        self.push_quiz(ui);
    }

    fn reset_quiz_screen(&mut self, ui: &MainWindow) {
        self.quiz_index = 0;
        self.quiz_correct = 0;
        for q in &mut self.quiz {
            q.state0 = 0;
            q.state1 = 0;
            q.state2 = 0;
            q.state3 = 0;
            q.was_correct = false;
        }
        self.update_quiz_property(ui);
        self.push_quiz(ui);
    }

    fn pick_answer(&mut self, ui: &MainWindow, option: i32) {
        if self.quiz.is_empty() || ui.get_quiz_phase() == 1 || ui.get_quiz_done() {
            return;
        }
        let idx = self.quiz_index;
        let q = &mut self.quiz[idx];
        let correct_index = q.answer;
        let correct = option == correct_index;
        q.was_correct = correct;
        for i in 0..4 {
            let state = if i == correct_index {
                3
            } else {
                4
            };
            let state = if i == option {
                if correct {
                    1
                } else {
                    2
                }
            } else {
                state
            };
            match i {
                0 => q.state0 = state,
                1 => q.state1 = state,
                2 => q.state2 = state,
                _ => q.state3 = state,
            }
        }
        if correct {
            self.quiz_correct += 1;
        }
        self.push_quiz(ui);
        ui.set_quiz_phase(1);
    }

    fn next_question(&mut self, ui: &MainWindow) {
        if self.quiz.is_empty() {
            return;
        }
        if self.quiz_index + 1 < self.quiz.len() {
            self.quiz_index += 1;
            for q in &mut self.quiz {
                q.state0 = 0;
                q.state1 = 0;
                q.state2 = 0;
                q.state3 = 0;
                q.was_correct = false;
            }
            self.update_quiz_property(ui);
            self.push_quiz(ui);
        } else {
            let total = self.quiz.len() as i32;
            let score = if total > 0 {
                (self.quiz_correct * 100) / total
            } else {
                0
            };
            self.data.quiz_answered += self.quiz.len() as i32;
            self.data.set_best(self.lesson_id, score);
            self.data.xp += 20 + score / 10;
            self.save();

            ui.set_quiz_score(score);
            ui.set_quiz_correct(self.quiz_correct);
            ui.set_quiz_done(true);
            ui.set_quiz_result(quiz_result_title(score).into());
            ui.set_quiz_result_sub(quiz_result_sub(score, self.quiz_correct, total).into());
            self.refresh_lesson_ui(ui);
        }
    }

    // ------------------------------------------------------------------
    // Cheat sheet & settings
    // ------------------------------------------------------------------

    fn toggle_cheat(&mut self, ui: &MainWindow, id: i32) {
        if let Some(pos) = self.data.opened_cheats.iter().position(|x| *x == id) {
            self.data.opened_cheats.remove(pos);
        } else {
            self.data.opened_cheats.push(id);
        }
        self.save();
        self.push_cheatsheet(ui);
    }

    fn select_accent(&mut self, ui: &MainWindow, index: i32) {
        self.data.accent = index.clamp(0, 3);
        self.save();
        ui.set_accent_index(self.data.accent);
    }

    fn reset_progress(&mut self, ui: &MainWindow) {
        if ui.get_reset_armed() {
            self.data = SaveData {
                xp: 0,
                streak: 0,
                last_day: String::new(),
                best_quiz: 0,
                done: Vec::new(),
                best: Vec::new(),
                opened_cheats: vec![1],
                scenario: 0,
                scenario_line: 0,
                quiz_answered: 0,
                accent: 0,
            };
            self.lesson_id = 1;
            self.scenario_index = 0;
            self.scenario_step = 0;
            self.save();
            ui.set_reset_armed(false);
            self.refresh_all(ui);
        } else {
            ui.set_reset_armed(true);
        }
    }

    // ------------------------------------------------------------------
    // Code Lab
    // ------------------------------------------------------------------

    fn select_scenario(&mut self, ui: &MainWindow, index: i32) {
        self.data.scenario = index.clamp(0, self.scenarios.len() as i32 - 1);
        self.scenario_index = self.data.scenario as usize;
        self.scenario_step = 0;
        self.save();
        self.stop_playing(ui);
        self.push_scenario(ui);
    }

    fn step_prev(&mut self, ui: &MainWindow) {
        if self.scenario_step > 0 {
            self.scenario_step -= 1;
        }
        self.apply_scenario_step(ui);
    }

    fn step_next(&mut self, ui: &MainWindow, auto: bool) {
        let steps = self.scenarios[self.scenario_index].steps.len();
        if self.scenario_step + 1 < steps {
            self.scenario_step += 1;
        } else if auto {
            self.stop_playing(ui);
        }
        self.apply_scenario_step(ui);
    }

}

fn models<T: 'static>(values: Vec<T>) -> slint::ModelRc<T> {
    Rc::new(VecModel::from(values)).into()
}

fn quiz_progress(index: usize, total: usize) -> String {
    if total == 0 {
        "Question 1 of 1".into()
    } else {
        format!("Question {} of {}", index + 1, total)
    }
}

fn quiz_result_title(score: i32) -> &'static str {
    match score {
        100 => "Perfect score!",
        80..=99 => "Great job!",
        50..=79 => "Good effort!",
        _ => "Keep practicing!",
    }
}

fn quiz_result_sub(score: i32, correct: i32, total: i32) -> String {
    format!("You answered {correct} of {total} correctly · {score}%")
}

fn greeting() -> &'static str {
    "Welcome back! Today is a great day to become a Rustacean."
}

// ---------------------------------------------------------------------------
// Persistence
// ---------------------------------------------------------------------------

fn default_save_dir() -> PathBuf {
    if let Some(appdata) = std::env::var_os("APPDATA") {
        PathBuf::from(appdata).join("RustAcademy")
    } else {
        std::env::current_dir()
            .unwrap_or_else(|_| PathBuf::from("."))
            .join("rust-academy-data")
    }
}

fn load(dir: &Path) -> SaveData {
    let path = dir.join("rust-academy.json");
    std::fs::read(&path)
        .ok()
        .and_then(|bytes| serde_json::from_slice(&bytes).ok())
        .unwrap_or_default()
}

// ---------------------------------------------------------------------------
// Entry points
// ---------------------------------------------------------------------------

pub fn app_version() -> String {
    option_env!("RUST_ACADEMY_VERSION")
        .map(str::to_owned)
        .unwrap_or_else(|| env!("CARGO_PKG_VERSION").to_owned())
}

fn run_ui_with_dir(save_dir: PathBuf) {
    let ui = MainWindow::new().expect("failed to create Rust Academy UI");
    ui.set_version(app_version().into());
    ui.set_lessons_search(SharedString::default());
    ui.set_cheat_search(SharedString::default());
    ui.set_reset_armed(false);
    ui.set_playing(false);

    let state = Rc::new(RefCell::new(AppState::new(save_dir)));
    {
        let mut s = state.borrow_mut();
        s.refresh_all(&ui);
        s.push_scenario_names(&ui);
        s.navigate(&ui, 0);
    }

    // ---- wire callbacks --------------------------------------------------
    {
        let weak = ui.as_weak();
        let state = state.clone();
        ui.on_navigate(move |page| {
            if let Some(ui) = weak.upgrade() {
                state.borrow_mut().navigate(&ui, page);
            }
        });
    }
    {
        let weak = ui.as_weak();
        let state = state.clone();
        ui.on_open_lesson(move |id| {
            if let Some(ui) = weak.upgrade() {
                state.borrow_mut().open_lesson(&ui, id);
            }
        });
    }
    {
        let weak = ui.as_weak();
        let state = state.clone();
        ui.on_back(move || {
            if let Some(ui) = weak.upgrade() {
                state.borrow_mut().go_back(&ui);
            }
        });
    }
    {
        let weak = ui.as_weak();
        let state = state.clone();
        ui.on_mark_complete(move || {
            if let Some(ui) = weak.upgrade() {
                state.borrow_mut().mark_complete(&ui);
            }
        });
    }
    {
        let weak = ui.as_weak();
        let state = state.clone();
        ui.on_start_quiz(move || {
            if let Some(ui) = weak.upgrade() {
                let mut s = state.borrow_mut();
                s.reset_quiz_data(&ui);
                ui.set_page(3);
            }
        });
    }
    {
        let weak = ui.as_weak();
        let state = state.clone();
        ui.on_quiz_pick(move |option| {
            if let Some(ui) = weak.upgrade() {
                state.borrow_mut().pick_answer(&ui, option);
            }
        });
    }
    {
        let weak = ui.as_weak();
        let state = state.clone();
        ui.on_quiz_next(move || {
            if let Some(ui) = weak.upgrade() {
                state.borrow_mut().next_question(&ui);
            }
        });
    }
    {
        let weak = ui.as_weak();
        let state = state.clone();
        ui.on_quiz_retry(move || {
            if let Some(ui) = weak.upgrade() {
                state.borrow_mut().reset_quiz_screen(&ui);
            }
        });
    }
    {
        let weak = ui.as_weak();
        let state = state.clone();
        ui.on_select_scenario(move |index| {
            if let Some(ui) = weak.upgrade() {
                state.borrow_mut().select_scenario(&ui, index);
            }
        });
    }
    {
        let weak = ui.as_weak();
        let state = state.clone();
        ui.on_step_prev(move || {
            if let Some(ui) = weak.upgrade() {
                state.borrow_mut().step_prev(&ui);
            }
        });
    }
    {
        let weak = ui.as_weak();
        let state = state.clone();
        ui.on_step_next(move || {
            if let Some(ui) = weak.upgrade() {
                state.borrow_mut().step_next(&ui, false);
            }
        });
    }
    {
        let weak = ui.as_weak();
        let state = state.clone();
        ui.on_step_play(move || {
            if let Some(ui) = weak.upgrade() {
                let mut s = state.borrow_mut();
                if s.playing {
                    s.stop_playing(&ui);
                } else {
                    s.playing = true;
                    ui.set_playing(true);

                    let weak2 = weak.clone();
                    let state2 = state.clone();
                    let timer = Timer::default();
                    timer.start(
                        TimerMode::Repeated,
                        Duration::from_millis(900),
                        move || {
                            if let Some(ui) = weak2.upgrade() {
                                let mut s2 = state2.borrow_mut();
                                if s2.playing {
                                    s2.step_next(&ui, true);
                                }
                            }
                        },
                    );
                    s.timer = Some(timer);
                }
            }
        });
    }
    {
        let weak = ui.as_weak();
        let state = state.clone();
        ui.on_lessons_search_changed(move |text| {
            if let Some(ui) = weak.upgrade() {
                ui.set_lessons_search(text);
            }
        });
    }
    {
        let weak = ui.as_weak();
        let state = state.clone();
        ui.on_cheat_search_changed(move |text| {
            if let Some(ui) = weak.upgrade() {
                ui.set_cheat_search(text);
            }
        });
    }
    {
        let weak = ui.as_weak();
        let state = state.clone();
        ui.on_toggle_cheat(move |id| {
            if let Some(ui) = weak.upgrade() {
                state.borrow_mut().toggle_cheat(&ui, id);
            }
        });
    }
    {
        let weak = ui.as_weak();
        let state = state.clone();
        ui.on_select_accent(move |index| {
            if let Some(ui) = weak.upgrade() {
                state.borrow_mut().select_accent(&ui, index);
            }
        });
    }
    {
        let weak = ui.as_weak();
        let state = state.clone();
        ui.on_reset(move || {
            if let Some(ui) = weak.upgrade() {
                state.borrow_mut().reset_progress(&ui);
            }
        });
    }
    {
        let weak = ui.as_weak();
        let state = state.clone();
        ui.on_open_about(move || {
            if let Some(ui) = weak.upgrade() {
                ui.set_page(8);
            }
        });
    }

    // Keep the models alive for as long as the window exists (not needed for
    // the running window, but harmless).
    drop(state);

    ui.run().expect("Slint event loop failed");
}

/// Public entry point used by the Windows executable.
pub fn run_ui() {
    run_ui_with_dir(default_save_dir());
}

#[cfg(target_os = "android")]
#[no_mangle]
pub extern "C" fn android_main(app: slint::android::AndroidApp) {
    let save_dir = app
        .internal_data_path()
        .unwrap_or_else(|| std::env::temp_dir().join("rust-academy"));
    slint::android::init(app).expect("failed to initialise Slint Android backend");
    run_ui_with_dir(save_dir);
}
